app: {}
dataset:
  add_noise_to_train_poses: false
  bg_color: white
  dataset_center_idx: 10
  dataset_num_workers: 6
  dataset_path: ~/datasets/SB_20
  dataset_type: multiview
  get_normals: false
  load_modes:
  - imgs
  - semantics
  - instance
  - preds_deeplab
  mip: 0
  mode_mesh_norm: sphere
  model_rescaling: largest
  multiview_dataset_format: sb20
  num_rays_sampled_per_img: 4096
  num_samples: 100000
  num_samples_on_mesh: 100000000
  offset: null
  pose_noise_strength: 0.01
  sample_mode:
  - rand
  - near
  - near
  - trace
  - trace
  sample_tex: false
  samples_per_voxel: 2
  scale: null
  val_mip: 2
  voxel_raymarch_epoch_start: 201
embedder:
  embedder_type: positional
  pos_multires: 10
  view_multires: 4
global:
  config: _results/logs/runs/retrain_best/00688/20230618-170421/config.yaml
  default_channel: rgb
  detect_anomaly: false
  exp_name: test_panop_start_400_prune_at_201_voxel_201_2_2_iw_1000_ireg_1
  perf: false
  trainer_type: PanopticTrainer
grid:
  as_type: none
  base_lod: 2
  capacity_log_2: 18
  coarsest_scale: 1.0
  codebook_bitwidth: 8
  delta_capacity_log_2: 18
  feature_bias: 0.0
  feature_dim: 2
  feature_std: 0.0
  finest_scale: 0.0001
  grid_type: PermutoGrid
  interpolation_type: linear
  max_grid_res: 2048
  multiscale_type: cat
  noise_std: 0.0
  num_lods: 24
  raymarch_type: ray
  tree_type: quad
net:
  activation_type: relu
  contrast_sem_weight: 0.0
  decoder_type: basic
  hidden_dim: 64
  inst_detach: true
  inst_direct_pos: false
  inst_hidden_dim: 64
  inst_num_layers: 2
  inst_sigmoid: false
  inst_softmax: true
  layer_type: none
  nef_type: PanopticDeltaNeF
  num_classes: 20
  num_instances: -1
  num_layers: 1
  out_dim: 1
  position_input: false
  pretrained: null
  sem_activation_type: null
  sem_cascade: false
  sem_conf_enable: false
  sem_detach: true
  sem_epoch_start: 401
  sem_hidden_dim: 64
  sem_normalize: false
  sem_num_layers: 1
  sem_sigmoid: false
  sem_softmax: true
  sem_temperature: 1.0
  separate_sem_grid: false
  skip: null
optimizer:
  delta_grid_lr_weight: 100
  delta_grid_tvl1_reg: 0.0
  delta_grid_tvl2_reg: 0.0
  extrinsics_lr: 0.0001
  grid_lr_weight: 100
  grid_tvl1_reg: 0.0
  grid_tvl2_reg: 0.0
  inst_weight: 1000.0
  lr: 0.001
  lr_div_factor: 10000.0
  lr_scheduler_type: step
  lr_step_gamma: 0.1
  lr_step_size: 0
  lr_warmup_epochs: 0
  optimizer_type: adam
  ray_sparcity_reg: 0.0
  rgb_weight: 10
  sem_weight: 0.1
  tv_edge_num_samples: 100
  tv_window_size: 0.0001
  use_lr_scheduler: false
  weight_decay: 0
optional arguments:
  help: null
  log_level: 20
positional arguments: {}
renderer:
  ao: false
  camera_clamp:
  - 0
  - 10
  camera_fov: 30
  camera_lookat:
  - 0
  - 0
  - 0
  camera_origin:
  - -3.0
  - 0.65
  - -3.0
  camera_proj: persp
  matcap_path: data/matcaps/matcap_plastic_yellow.jpg
  min_dis: 0.0003
  num_steps: 512
  num_val_frames_to_save: 15
  ray_max_travel: 2.0
  render_batch: 8000
  render_res:
  - 1024
  - 1024
  shading_mode: rb
  shadow: false
  step_size: 1.0
  tracer_type: PanopticPackedRFTracer
trainer:
  base_temperature: 0.07
  batch_size: 6
  clustering_epoch_start: 0
  epochs: 800
  extrinsics_epoch_end: 900
  extrinsics_epoch_start: 0
  grow_every: -1
  growth_strategy: increase
  inst_conf_enable: false
  inst_dist_func: cos
  inst_epoch_start: 401
  inst_loss: linear_assignment_things
  inst_normalize: false
  inst_num_dilations: -1
  inst_pn_ratio: 0.5
  inst_segment_reg_weight: 1.0
  inst_soft_temperature: 0.0
  inst_temperature: 0.07
  lod_annel_epoch_start: 0
  lod_annel_epochs: 400
  lod_anneling: false
  log_2d: false
  log_dir: _results/logs/runs/sb20_best
  log_sub_losses: false
  model_format: full
  num_clustering_samples: 20000
  num_clustering_workers: 6
  only_last: false
  optimize_extrinsics: true
  optimize_val_extrinsics: true
  prune_at_epoch: -1
  prune_every: 201
  random_lod: false
  render_every: -1
  render_val_labels: true
  resample: false
  resample_every: 1
  save_as_new: true
  save_every: 200
  sem_segment_reg_weight: 0.0
  val_extrinsics_end: 900
  val_extrinsics_every: 10
  val_extrinsics_start: 1
  weight_class_inbalance: false
validation:
  valid_every: 100
  valid_only: false
  valid_split: val
