# Copyright (c) 2022, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
#
# NVIDIA CORPORATION & AFFILIATES and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION & AFFILIATES is strictly prohibited.

global:
    exp_name: 'pc_nerf_vis'
    default_channel: 'rgb'

optimizer:
    optimizer_type: 'rmsprop'
    lr: 0.001
    use_lr_scheduler: False

dataset:
    dataset_type: 'multiview'
    multiview_dataset_format: 'replica'
    num_rays_sampled_per_img: 2048 #4096
    mip: 0
    val_mip: 2
    bg_color: 'black'
    load_modes: ['imgs', 'semantics','instance', 'panoptic_preds_ade20k_mask2former'] #,'instance']
    
    dataset_path: '[path_to_replica_prerenders]/office_3/Sequence_1'
    model_rescaling: 'largest' #'snap_to_bottom'

renderer:
    tracer_type: 'PackedRFTracer'
    num_steps: 350
    raymarch_type: ray
    render_batch: 2000 #4000
    camera_origin:
        - -3.0
        - 0.65
        - -3.0
    shading_mode: 'rb'
    render_res:
        - 1024
        - 1024

trainer:
    trainer_type: 'PanopticTrainer'
    epochs: 400
    batch_size: 3
    model_format: 'full'
    valid_every: 50
    save_every: 100
    render_every: 10
    sem_weight: 1e-2
    prune_every: 20

    num_val_frames_to_save: 15

    render_every: -1
    valid_every: 50
    save_every: 50
    save_as_new: true


    lod_anneling: False
    lod_annel_epochs: 10

    num_clustering_samples: 20000
    num_clustering_workers: 4

    # instance parameters
    inst_epoch_start: 0
    inst_weight: 1e-2
    
    inst_normalize: False
    inst_loss: sup_contrastive

    inst_epoch_start: -1 #200
    sem_epoch_start: -1 #200


# Instant-NGP encoding
grid:
    grid_type: 'HashGrid'
    num_lods: 14
    interpolation_type: 'linear'
    multiscale_type: 'cat'
    feature_dim: 2
    feature_std: 0.01
    tree_type: 'geometric'
    max_grid_res: 2048
    codebook_bitwidth: 19

net:
    nef_type: 'MeanShiftContrastiveNef'
    hidden_dim: 64
    num_layers: 1
    num_classes: 20
    sem_hidden_dim: 64

    sem_num_layers: 2
    sem_hidden_dim: 64

    inst_num_layers: 2
    inst_hidden_dim: 64

    sem_detach: True
    inst_detach: True

    pretrained: [path_to_pretrained]

embedder:
    embedder_type: 'positional'
