# Copyright (c) 2022, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
#
# NVIDIA CORPORATION & AFFILIATES and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION & AFFILIATES is strictly prohibited.

global:
    exp_name: 'semantic-contrastive'

optimizer:
    optimizer_type: 'adam'
    # optimizer_type: 'sgd'
    # optimizer_type: 'rmsprop'
    
    # weight_decay: 0.0005
    
    lr: 0.001
    lr_warmup_epochs: 0
    lr_div_factor: 1e4
    use_lr_scheduler: False

dataset:
    dataset_type: 'multiview'
    multiview_dataset_format: 'blender'
    num_rays_sampled_per_img: 4096
    mip: 2
    bg_color: 'white'
    load_modes: ['imgs', 'cam_poses', 'cam_params', 'semantics','instance_shuffled'] #,'instance']
    scale: 0.116 # ~2/17,25
    offset: [0., 0., -1.]
    
    dataset_path: '~/data/simple_monkeys'

renderer:
    tracer_type: 'PackedRFTracer'
    num_steps: 512
    raymarch_type: ray
    render_batch: 4000
    camera_origin:
        - -3.0
        - 0.65
        - -3.0
    shading_mode: 'rb'
    render_res:
        - 1024
        - 1024

trainer:
    trainer_type: 'SemanticContrastiveTrainer'
    epochs: 50
    batch_size: 3
    model_format: 'full'
    valid_every: 50
    save_every: 10
    render_every: 10
    sem_weight: 1e-2

    # growth_strategy: 'finetocoarse'
    # growth_strategy: 'increase'
    # grow_every: 2

    lod_anneling: False
    lod_annel_epochs: 10

    # instance parameters
    inst_epoch_start: 0
    inst_weight: 1e-2
    
    inst_normalize: True
    inst_dist_func: 'cos' # ['l1', 'l2', 'cos']
    # inst_loss: 'vicreg'
    # inst_loss: 'vicreg_center'
    inst_loss: sup_contrastive
    weight_class_inbalance: False
    sim_coeff: 25.0
    std_coeff: 500.0
    cov_coeff: 10.0

    log_sub_losses: True


    


    # inst_loss: 'SupConLoss'
    # temperature: 0.07
    # num_anchors: 20

# Instant-NGP encoding
# grid:
#     grid_type: 'HashGrid'
#     num_lods: 16
#     interpolation_type: 'linear'
#     multiscale_type: 'cat'
#     feature_dim: 2
#     feature_std: 0.01
#     tree_type: 'geometric'
#     max_grid_res: 2048
#     codebook_bitwidth: 19

# Triplanar encoding
grid:
    grid_type: 'TriplanarGrid'
    interpolation_type: 'linear'
    multiscale_type: 'cat'
    feature_dim: 4
    feature_std: 0.01
    base_lod: 5
    num_lods: 4

net:
    nef_type: 'SemanticContrastiveNeF'
    hidden_dim: 64
    num_layers: 1
    num_classes: 20
    sem_hidden_dim: 64

    sem_detach: True
    inst_detach: True

    # hash grid cat
    # pretrained: '_results/logs/runs/semantic-contrastive-app/20221209-174230/model.pth'
    
    # triplanar grid cat
    # pretrained: '_results/logs/runs/semantic-contrastive-app/20221213-154706/model.pth'
    # pretrained: '_results/logs/runs/semantic-contrastive-app/20230118-151955/model.pth'
    # model_format: 'params_only'

embedder:
    embedder_type: 'positional'
